version: '3.9'
services:
  api:
    build: .
    container_name: graph-rag-api
    ports:
      - '8000:8000'
    env_file: .env
    depends_on:
      - postgres
      - neo4j
    volumes:
      - ./:/app
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: ${PGDATABASE:-energy}
      POSTGRES_USER: ${PGUSER:-energy}
      POSTGRES_PASSWORD: ${PGPASSWORD:-energy}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  neo4j:
    image: neo4j:5.22
    environment:
      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-pleasechangeme}
      NEO4J_dbms_security_procedures_unrestricted: algo.*,apoc.*
      NEO4JLABS_PLUGINS: '["apoc"]'
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - neo4jdata:/data
volumes:
  pgdata:
  neo4jdata:
