name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: ruff check .
      - run: mypy src
      - run: pytest -q
        env:
          MOCK_OPENAI: '1'
          OPENAI_API_KEY: 'test-key'
      - run: docker build -t graph-rag-pipeline .
